# -*- coding: utf-8 -*-
"""Text-to-Image LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UChd_-rY4EU0sTL3YrFH-eGGYlQh1bi
"""

!pip install diffusers transformers accelerate

!pip install diffusers transformers accelerate safetensors huggingface_hub

!huggingface-cli login --token #"HuuginFace Token Here"

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
import IPython.display as display

# Use the correct model
model_id = "runwayml/stable-diffusion-v1-5"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Adjust data type based on device
torch_dtype = torch.float16 if device == "cuda" else torch.float32

# Load the pipeline
pipe = StableDiffusionPipeline.from_pretrained(
    model_id, torch_dtype=torch_dtype
)
pipe.to(device)

# Function to generate an image
def generate_image(prompt_text):
    image = pipe(prompt_text, guidance_scale=8.5).images[0]
    image.save("generated_image.png")
    display.display(Image.open("generated_image.png"))

# Input prompt and generate image
prompt = input("Enter your image prompt: ")
generate_image(prompt)